name: Clang Format Linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          FILES=$(find . -name '*.cpp' -o -name '*.h')
          clang-format --dry-run --Werror $FILES
