name: Clang Format Linter and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          FILES=$(find . -name '*.cpp' -o -name '*.h')
          clang-format --dry-run --Werror $FILES

  build:
    runs-on: ubuntu-latest
    needs: clang-format-check
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ python3-pip

      - name: Install Conan
        run: pip3 install conan==1.*

      - name: Conan install
        run: |
          mkdir build
          conan install . -if=build -s compiler.libcxx=libstdc++11 -s build_type=Release -g cmake --build=missing

      - name: Configure CMake
        run: cmake -B build

      - name: Build project
        run: cmake --build build
        
